CREATE TABLE IF NOT EXISTS social_links (
  social_id INT AUTO_INCREMENT PRIMARY KEY,
  platform VARCHAR(50) NOT NULL,
  icon_class VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  sort_order INT DEFAULT 999,
  status ENUM('active','inactive') DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
